restart-prompt-title = Reiniciar { -brand-short-name }
restart-prompt-question = ¿Está seguro que desea reiniciar { -brand-short-name }?
appmenuitem-restart-browser =
    .label = Reiniciar
copy-url =
    .label = Copiar enlace pestaña
copy-all-urls =
    .label = Copiar todos los enlaces a la pestaña
unload-tab =
    .label = Descargar pestaña
open-all-private =
    .label = Abrir todo en Pestañas Privadas
open-all-links-private =
    .label = Abrir todos los enlaces en pestañas privadas
open-private-tab =
    .label = Abrir en una nueva pestaña privada
new-private-tab =
    .label = Nueva pestaña privada
    .tooltiptext = Abrir una nueva pestaña privada
open-link-private =
    .label = Abrir enlace en nueva pestaña privada
status-bar =
    .label = Barra de estado
tab-position-header = Posición de la barra de pestaña
tab-bar-top-above =
    .label = Arriba, encima de la barra de direcciones
tab-bar-top-below =
    .label = Arriba, debajo de la barra de direcciones
tab-bar-bottom-above =
    .label = Abajo, encima de la barra de estado
tab-bar-bottom-below =
    .label = Abajo, debajo de la barra de estado
tab-additional-header = Preferencias adicionales de Tab
pinned-icon-only =
    .label = Contraer pestañas fijadas para mostrar sólo el icono del sitio
insert-after-current =
    .label = Insertar nueva pestaña después de la pestaña actual
insert-related-after-current =
    .label = Insertar nueva pestaña relacionada después de la pestaña actual
dynamic-theme-header = Temas Dinámicos
dynamic-theme-dark =
    .label = Forzar Modo Oscuro
dynamic-theme-light =
    .label = Forzar Modo Luz
dynamic-theme-auto =
    .label = Definir dinámicamente el modo Luz/Oscuro
restart-header = Reiniciar elemento de menú
restart-show-button =
    .label = Mostrar botón de reiniciar en PanelUI
restart-purge-cache =
    .label = Borrar caché de reinicio rápido al reiniciar el navegador
restart-require-confirmation =
    .label = Requiere confirmación de reinicio
tab-feature-header = Tab Context Menu
show-duplicate-tab =
    .label = Mostrar la opción «Duplicar pestaña»
show-copy-url =
    .label = Mostrar elemento del menú de la pestaña de copia
enable-copy-active-tab =
    .label = Copiar URL sólo desde la pestaña activa
show-copy-all-urls =
    .label = Mostrar copia de todas las urls de la pestaña
show-unload-tab =
    .label = Mostrar elemento de menú de pestaña de descarga
statusbar-enabled =
    .label = Mostrar barra de estado
statusbar-show-links =
    .label = Mostrar enlaces
statusbar-contrast-text =
    .label = Color de texto de la barra de estado contrastar
bookmarks-bar-position-header = Posición de la barra de marcadores
bookmarks-position-top =
    .label = Subir
bookmarks-position-bottom =
    .label = Abajo
geolocation-api-header = API de geolocalización
geolocation-description = Algunos sitios web requieren su ubicación para funcionar. Si un sitio web no funciona debido a que no puede encontrar su ubicación, por favor habilite esta preferencia y vuelva a intentarlo.
geolocation-api-enabled =
    .label = Activar
geolocation-api-disabled =
    .label = Desactivar
send-referrer-header-0 =
    .label = Nunca enviar la cabecera del remitente
send-referrer-header-1 =
    .label = Enviar la cabecera del remitente sólo cuando haga clic en enlaces y elementos similares
send-referrer-header-2 =
    .label = Enviar la cabecera del remitente a todas las peticiones (por defecto)
enable-webrtc-p2p =
    .label = Habilitar la conexión entre pares WebRTC
load-images =
    .label = Cargar imágenes automáticamente
enable-javascript =
    .label = Activar JavaScript
webrtc-header = Conexión con pares WebRTC
ref-header = Encabezado de HTTP
statusbar-header = Barra de estado
private-tab =
    .label =
        { $isPrivate ->
            [true] Salir de la pestaña privada
           *[false] Hacer pestaña privada
        }
update-application-manual =
    .label = No buscar actualizaciones nunca (no recomendado)
    .accesskey = N
preferences-doh-setting-ultra =
    .label = Protección Ultra
    .accesskey = U
preferences-doh-ultra-desc = { -brand-short-name } utilizará DNS seguro con Oblivious HTTP a través del relé de privacidad de Waterfox para una protección máxima.
preferences-doh-ultra-detailed-desc-1 = Utiliza el relé de Oblivious HTTP de Waterfox para ocultar las consultas DNS incluso al propio proveedor de DNS
preferences-doh-ultra-detailed-desc-2 = Proporciona una capa adicional de cifrado más allá del estándar DNS sobre HTTPS
preferences-doh-ultra-detailed-desc-3 = Máxima protección de privacidad DNS: nadie puede ver qué sitios visitas
preferences-doh-ultra-fallback-mode = Comportamiento alternativo:
preferences-doh-ultra-fallback-allowed = Permitir el uso del DNS del sistema si falla el DNS seguro
preferences-doh-ultra-fallback-disabled = No recurrir nunca al DNS del sistema (los sitios pueden no cargarse si falla el DNS seguro)
animation-header = Animaciones
appearance-header = Apariencia
autohide-hidden-header = Auto-ocultar y ocultos
bookmark-header = Barra de marcadores
center-header = Centrar
font-header = Fuentes
full-screen-header = Pantalla completa
icons-header = Iconos
interface-component-header = Componentes de la interfaz
media-player-header = Reproductor multimedia
nav-bar-header = Barra de navegación
panels-header = Paneles
rounding-header = Redondeo
sidebar-header = Barra lateral
tab-bar-header = Barra de pestañas
theme-header = Tema
lepton-style =
    .label = Estilo Lepton
proton-style =
    .label = Estilo Proton
close-button-hover =
    .label = Mostrar el botón de cerrar pestaña al pasar el cursor sobre la pestaña seleccionada cuando hay muchas pestañas abiertas
compact-bookmark-menu =
    .label = Reducir el espaciado del menú de marcadores
compact-context-menu =
    .label = Reducir el espaciado del menú contextual
compact-navbar-popup =
    .label = Reducir el espaciado del menú emergente de la barra de navegación
compact-panel-header =
    .label = Reducir el espaciado del encabezado del panel
disable-sidebar-animate =
    .label = Desactivar la animación del panel lateral
drag-space =
    .label = Activar espacio fijo para arrastrar
enable-cyan-accent-color =
    .label = Color de acento cian
enable-default-accent-color =
    .label = Color de acento predeterminado
enable-menu-transparency =
    .label = Activar la transparencia del menú
enable-panel-transparency =
    .label = Activar la transparencia del panel
enable-system-accent-color =
    .label = Color de acento del sistema
enable-waterfox-theme-0 =
    .label = Activar las personalizaciones de tema de Waterfox en todos los temas
enable-waterfox-theme-1 =
    .label = Activar las personalizaciones de tema de Waterfox solo en los temas de Waterfox
enable-waterfox-theme-2 =
    .label = Desactivar las personalizaciones de tema de Waterfox
full-panel-strip =
    .label = Separador del menú de la aplicación de ancho completo
remove-panel-strip =
    .label = Eliminar el separador de color del menú de la aplicación
hide-all-icons =
    .label = Ocultar todos los iconos
hide-bookmarkbar-icon =
    .label = Ocultar los iconos de la barra de marcadores
hide-bookmarkbar-label =
    .label = Ocultar las etiquetas de la barra de marcadores
hide-disabled-menuitems =
    .label = Ocultar los elementos de menú deshabilitados
hide-sidebar-header =
    .label = Ocultar el encabezado de la barra lateral
hide-tab-icons =
    .label = Ocultar los iconos de las pestañas
hide-urlbar-iconbox =
    .label = Ocultar el recuadro de iconos de la barra de direcciones
monospace-font =
    .label = Activar fuente monoespaciada para la página
monospace-font-theme =
    .label = Activar fuente monoespaciada para el tema
show-mac-menu-icons =
    .label = Mostrar iconos del menú en macOS
show-menu-icons =
    .label = Mostrar los iconos del menú
square-button-edges =
    .label = Esquinas cuadradas en los botones
square-checkbox =
    .label = Casilla de verificación cuadrada
square-field =
    .label = Esquinas cuadradas en los campos de entrada
square-menu-item =
    .label = Esquinas cuadradas en los elementos del menú contextual
square-menu-panel =
    .label = Esquinas cuadradas en el panel del menú de la aplicación
square-menu-popup =
    .label = Esquinas cuadradas en el panel del menú contextual
square-panel-item =
    .label = Esquinas cuadradas en los elementos del menú de la aplicación
square-tab-edges =
    .label = Esquinas cuadradas en las pestañas
tab-context-line =
    .label = Línea de contexto de pestañas
telemetry-page-subtitle = Waterfox no recopila telemetría sobre tu instalación: todos los módulos de telemetría se desactivan al compilar el navegador. Lo que haces en tu navegador solo lo sabes tú.
telemetry-privacy-policy = Política de privacidad
onboarding-grassroots-title = Apoyando el movimiento de base
onboarding-grassroots-subtitle = Gracias por usar Waterfox, un navegador independiente y de base comunitaria. Con tu apoyo, estamos construyendo una alternativa sostenible frente a los grandes actores del sector.
tabbrowser-confirm-session-restore-checkbox = Abrir las ventanas y pestañas anteriores
pane-tree-title = Pestañas verticales en árbol
category-tree =
    .tooltiptext = { pane-tree-title }
browser-layout-tree-vertical-tabs =
    .label = Pestañas verticales en árbol
sidebar-tree-vertical-tabs =
    .label = Pestañas verticales en árbol
tree-header = Pestañas verticales en árbol
tree-appearance-header = Apariencia
tree-auto-sticky-header = Pestañas fijadas a los bordes de la barra cuando salen de la vista al desplazarse
tree-faviconize-pinned-tabs =
    .label = Mostrar las pestañas ancladas solo con su icono
    .accesskey = S
tree-sticky-active-tab =
    .label = Pestaña activa
    .accesskey = k
tree-sticky-sharing-tab =
    .label = Pestañas que comparten cámara/micrófono/pantalla
    .accesskey = g
tree-sticky-sound-playing-tab =
    .label = Pestañas con sonido en reproducción
    .accesskey = y
tree-behavior-header = Vista en árbol de las pestañas
tree-auto-collapse-expand-subtree-on-attach =
    .label = Cuando aparece un nuevo árbol, contraer automáticamente los demás
    .accesskey = c
tree-auto-collapse-expand-subtree-on-select =
    .label = Al enfocar una pestaña, expandir su árbol y contraer las demás automáticamente
    .accesskey = x
tree-drop-links-on-tab-behavior-caption =
    .value = Cuando se suelta un enlace o una URL sobre una pestaña
    .accesskey = l
tree-drop-links-on-tab-behavior-ask =
    .label = Preguntarme siempre cómo tratarlo
tree-drop-links-on-tab-behavior-load =
    .label = Cargar en la pestaña
tree-drop-links-on-tab-behavior-newtab =
    .label = Abrir una nueva pestaña hija
tree-successor-tab-control-level-caption =
    .value = Cuando la pestaña actual se cierra siendo la última hija
    .accesskey = h
tree-successor-tab-control-level-in-tree =
    .label = Enfocar la pestaña anterior en el árbol
tree-successor-tab-control-level-never =
    .label = Enfocar siempre la siguiente pestaña (respetar el control del navegador o de otras extensiones)
tree-successor-tab-control-level-simulate-default =
    .label = Enfocar siempre la siguiente pestaña
tree-tree-double-click-behavior-caption =
    .value = Doble clic en una pestaña
    .accesskey = D
tree-tree-double-click-behavior-toggle-close =
    .label = Cerrar pestaña
tree-tree-double-click-behavior-toggle-collapsed =
    .label = Contraer/expandir árbol
tree-tree-double-click-behavior-toggle-none =
    .label = No hacer nada
tree-tree-double-click-behavior-toggle-sticky =
    .label = Fijar a los bordes de la barra de pestañas / Desfijar de los bordes de la barra de pestañas
tree-auto-attach-header = Organización automática del árbol de pestañas
tree-auto-attach-child-end =
    .label = Último hijo de la pestaña principal
tree-auto-attach-child-next-to-last-related-tab =
    .label = Hijo de la pestaña principal, junto al hijo abierto recientemente
tree-auto-attach-child-top =
    .label = Primer hijo de la pestaña principal
tree-auto-attach-independent =
    .label = Pestaña independiente
tree-auto-attach-next-sibling =
    .label = Siguiente hermano de la pestaña principal
tree-auto-attach-no-control =
    .label = (sin control)
tree-auto-attach-sibling =
    .label = Hermano de la pestaña principal
tree-auto-attach-on-any-other-trigger-caption =
    .value = Pestañas desde cualquier otro origen: Abrir como
    .accesskey = t
tree-auto-attach-on-duplicated-caption =
    .value = Duplicar la pestaña como
    .accesskey = u
tree-auto-attach-on-new-tab-button-middle-click-caption =
    .value = Al hacer clic central, abrir nueva pestaña en blanco como
    .accesskey = m
tree-auto-attach-on-new-tab-command-caption =
    .value = Abrir nueva pestaña en blanco como
    .accesskey = n
tree-auto-attach-on-opened-from-external-caption =
    .value = Nueva pestaña desde otras aplicaciones: Abrir como
    .accesskey = A
tree-auto-attach-on-opened-with-owner-caption =
    .value = Cuando una pestaña se abre desde otra existente, abrirla como
    .accesskey = D
tree-auto-attach-same-site-orphan-caption =
    .value = Nueva pestaña con el mismo sitio que la actual desde la barra de direcciones, marcadores, historial u otros: Abrir como
    .accesskey = w
tree-insert-new-tab-from-pinned-tab-at-caption =
    .value = Posición de inserción de nuevas pestañas hijas desde pestañas ancladas (aparecerán como pestañas raíz)
    .accesskey = p
tree-insert-new-tab-from-pinned-tab-at-end =
    .label = Al final del árbol
tree-insert-new-tab-from-pinned-tab-at-next-to-last-related-tab =
    .label = Junto al hijo abierto recientemente o cerca de la pestaña de origen
tree-insert-new-tab-from-pinned-tab-at-no-control =
    .label = Sin control (respetar la decisión del navegador o de otras extensiones)
tree-insert-new-tab-from-pinned-tab-at-top =
    .label = En la parte superior del árbol (cerca de la pestaña de origen)
